CREATE TABLE `eqms_commission_order` (
                                         `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
                                         `commission_no` varchar(50) NOT NULL COMMENT '委托单编号',
                                         `plan_no` varchar(50) DEFAULT NULL COMMENT '计划编号',
                                         `standard_item_no` varchar(50) DEFAULT NULL COMMENT '标准项目编号',
                                         `equipment_name` varchar(200) DEFAULT NULL COMMENT '设备名称',
                                         `project_name` varchar(200) DEFAULT NULL COMMENT '工程项目名称',
                                         `expected_start_date` datetime DEFAULT NULL COMMENT '预计施工日期',
                                         `expected_end_date` datetime DEFAULT NULL COMMENT '预计完工日期',
                                         `repair_reason` varchar(500) DEFAULT NULL COMMENT '请修原因',
                                         `construction_team_code` varchar(50) DEFAULT NULL COMMENT '施工班代码',
                                         `construction_team_name` varchar(100) DEFAULT NULL COMMENT '施工班名称',
                                         `project_category` varchar(50) DEFAULT NULL COMMENT '项目类别',
                                         `commission_date` datetime DEFAULT NULL COMMENT '委托日期',
                                         `commissioner` varchar(50) DEFAULT NULL COMMENT '委托人',
                                         `inspector_name` varchar(50) DEFAULT NULL COMMENT '点检姓名',
                                         `status` char(1) DEFAULT '0' COMMENT '状态（0正常 1停用）',
                                         `sync_status` char(1) DEFAULT '0' COMMENT '同步状态（0未处理 1已接收 2处理中 3已完成 4失败）',
                                         `sync_time` datetime DEFAULT NULL COMMENT '同步时间',
                                         `sync_message` varchar(500) DEFAULT NULL COMMENT '同步消息',
                                         `create_by` varchar(64) DEFAULT '' COMMENT '创建者',
                                         `create_time` datetime DEFAULT NULL COMMENT '创建时间',
                                         `update_by` varchar(64) DEFAULT '' COMMENT '更新者',
                                         `update_time` datetime DEFAULT NULL COMMENT '更新时间',
                                         `remark` varchar(500) DEFAULT NULL COMMENT '备注',
                                         PRIMARY KEY (`id`),
                                         UNIQUE KEY `uniq_commission_no` (`commission_no`),
                                         KEY `idx_plan_no` (`plan_no`),
                                         KEY `idx_status` (`status`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='EQMS委托单信息表';